### ISSUE TITLE
Upload audio in mp3 and other file formats to Heart

### ISSUE THREAD

**Issue by CharlieMiab** [museuminabox/brain#123]
When creating/editing object audio we can currently only upload in .wav file formats, this is likely to add an additional hurdle for many users.

**Comment by amcewen** [comment]
I think this is more a `heart` issue than a `brain` issue - we chose `.wav` files because they start playing a second or two faster (as there's no decoding to do) when you boop an object.

We _could_ do the conversion on `brain`, but it's more sensible to do it when the file is first uploaded, so that'd be on `heart`.

I've moved this over to https://github.com/museuminabox/museuminabox-v2/issues/213
