### ISSUE TITLE
How do we update the software for a Brain?

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#19]
There are an assortment of dependencies for a Brain - Node RED, the RFID code, the Node-RED flow, etc.

It will make life much easier if there's a simple way to push updates out to the various brains, even just for the different MiaB offices, and longer-term as they venture out into the wild...

**Comment by amcewen** [comment]
Hmm, plenty of options for ways to do this, and no obvious one to pick.
- Puppet
- Chef
- Docker
- Ubuntu Core
- Resin.io
- Canned .img files
- Ansible

## [Puppet](https://puppetlabs.com/)
- \+ Available in Raspbian. - I haven't used it before. - Generally requires a central server to provision things (not an issue long term, but not sure we need that right now)

## [Docker](https://www.docker.com/)
- \- Not available in Raspbian, but can be installed in Ubuntu Core and Resin.io.  - Few, if any, pre-rolled containers for ARM (the processor in the Pi).  + I'm already using it for mcqn.com, so there's no learning curve

## [Ansible](https://www.ansible.com/)
- \- Seems more tailored to inter-dependent server deployments.  - Not available in Raspbian.  - I haven't used it before.

## [Chef](https://www.chef.io/)
- \+ Available in Raspbian.  + Can run without a central, controlling server.  - I haven't used it before

## [Ubuntu Core](https://developer.ubuntu.com/en/snappy/start/raspberry-pi-2/)
- \+ Designed to solve this sort of problem.  + Available for Raspberry Pi 2 and above.  - Not available for Raspberry Pi 1 or Pi Zero.  + Allows easy rollback to earlier versions if there are problems with a new version.

## [Resin.io](https://resin.io/)
- \+ Designed to solve this sort of problem.  + Works on all Raspberry Pi models.  - Based on Yocto Linux (which I've not used much).  - $60/month once you've got more than 5 devices (and more as you grow).  + Uses Docker containers (although that will hit the same issues with a lack of pre-rolled containers).

## Canned .img files
- \+ Simplest option.  - Hard to track changes in source control.  - Difficult to upgrade systems once deployed (well, just as simple as initial install, but rather scorched earth about it, and can't be done remotely).

**Comment by infovore** [comment]
Just as a heads-up - I found Ansible much more straightforward for provisioning tiny, single things, than Chef Solo ever seemed to be: Chef Solo always felt like it was cut down from something large, wheras with Ansible, you can start with a single file with few dependencies; it's definitely not tailored to a particular shape of work.

The big question is how much can you rely on staying the same: if you can constrain changes to being in application code, rather than system-level, it becomes easier to push out changes to an application. Wheras if it's a moving target and you want to re-provision the entire system regularly... that becomes more challenging, I guess. But it might help simplify the requirements of provisioning if the goal isn't to reflash an entire image every time.

It might also be worth thinking about the push/pull model - you say 'push updates', but really, the model feels like it might be more 'make boxes aware there's an update to pull / box sets about acquiring said update'. (And: might be worth notifying people of the ideal bandwidth required)

There's also something something about user notification - how is someone made aware their box is updating and they should probably not touch it? (The answer might be 'emailing them at some point', there's clearly a tonne of conversations I don't know about).

**Comment by amcewen** [comment]
Good to get some actually-tried-it thoughts on Ansible/Chef, thanks!

And the rest of your comments are spot on too.  I think part of the problem is the tension between us having lots more experimentation to do and having our first commission, which is leading me towards wanting in-field updates and a good user experience.

Ubuntu Core has a mirrored file system, so installs the new version into an alternate partition and only switches to it when it's ready to run.  Which is a nice approach.  I don't know how well it does at resuming downloads/install if interrupted.

**Comment by amcewen** [comment]
Changed the title because we've got the initial install stuff as part of the fix for #17, but we don't currently have a strategy for updating the software once it's out in the wild.

**Comment by amcewen** [comment]
I think the updating fixes will be covered in #55, so closing this now.
