### ISSUE TITLE
Boop log feature requests

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#40]
- can it log the duration of the object on the reader? 
- can it cross-reference that to the length of the audio for that object?

We're wondering if we could reveal if there was a playback bug this way... i.e. if the object was still on the reader, but the audio track stopped at a duration that's different from the expected one. Ie, if the track was 60 seconds, but the playback stopped at 10 seconds, and the object was still on the brain.

We've also been chatting about having a basic recorder in the system. Something to help us measure how much people react to the stuff. What if the recorder could measure a basic decibel level in conjunction with the object being placed on the reader. (So you might roughly perceive a group laughing or talking etc)...

**Comment by george08** [comment]
Some visual sketches:

![image](https://user-images.githubusercontent.com/354542/36534926-fa090a68-17bf-11e8-8b4b-718df9044dd2.png)

![image](https://user-images.githubusercontent.com/354542/36534950-07db084e-17c0-11e8-91a8-e98d135307bd.png)

![image](https://user-images.githubusercontent.com/354542/36534989-1ce489ae-17c0-11e8-84bb-d4bf091405b0.png)

**Comment by george08** [comment]
@amcewen just chatting with phil about what we can possibly squeeze out of him in the remaining days until Friday... i'm wondering if it'd be possible to send a bit more data about a boop between now and then? if we could bash out something super rough along the lines above, that would be very exciting! (past boops notwithstanding :) )

**Comment by amcewen** [comment]
We could fairly easily add a(n optional, to continue to support boops from old brains) duration parameter, and have the boop be recorded when the object is removed (rather than when it's placed on the reader, as at present).

That should be reasonably easy for me to change the brains to support.  The only downside would be that you wouldn't see the boop happen while the object is on the brain (if there's a live update of the boop log on the heart site), it'd be just after.

Otherwise we'd have to have "boop on" and "boop off" APIs.  That's, if anything, slightly easier for me to implement, and slightly harder for Phil, but there's little in it.  

Having the brain understand the duration of a boop and report it feels a bit cleaner than inferring it server side, but I'm not hung up on that if we'd rather have the option of a nicer "live" view in the future.

**Comment by george08** [comment]
boop on + boop off sounds best to me. most accurate, most manipulable.

**Comment by george08** [comment]
Can you please implement that?

The reason I'm asking for it to be done soon (now?) is because the Smithsonian grant we've won is a baby version of a much bigger possible grant - maybe six figures - and therefore our and SI's evaluation of the baby grant is really important. For us to be able to demonstrate _literal usage_ would be huge. 

Phil had a great idea yesterday too, where you could actually _replay_ a session that actually happened by processing the boop log and knowing which tracks it refers to, playing/stopping them just like the kids did. Wouldn't that be amazing?!?!

**Comment by george08** [comment]
Can we show a filtered list of boops here?
https://museuminabox.herokuapp.com/backstage/boxes/box/62/change/

(It's practically impossible to tell which brain is which with the data we have in the Django app.)

Have made an issue in that repo:
https://github.com/museuminabox/museuminabox-v2/issues/32

**Comment by amcewen** [comment]
We've seen boops with a duration showing up in `heart`, so this has now been tested as well as implemented.
