### ISSUE TITLE
Keep UUID of Box if a software upgrade happens

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#64]
Right now, a Box's UUID would be overwritten (and a new Box created on Heart) if we upgrade the software on it. We would rather retain the Box in Heart as is, and note that it's been upgraded.

(Maybe we should store a software version on the Box?)

It would be nice if box.local had an "Upgrade Me" button.

**Comment by george08** [comment]
How about if there's an "I am Box `hardwareID`' form... and it can look up the UUID from Heart.

**Comment by amcewen** [comment]
We're going to add an `/upgrade` page to `box.local`. That will show a list of available boxes in an iframe on the right-hand side of the page, and a drag target on the left-hand side.

The user will then drag the relevant box from the list onto the drag target, in order to communicate the UUID to the box so it can configure itself.
