### ISSUE TITLE
Add Gillian & .wav to every Collection by default?

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#68]
There might be a more graceful way to do it, but can she also appear on box.local/prints so we can set her up while we're also doing/testing Wifi?

**Comment by amcewen** [comment]
I think longer term we should end up with a better way to manage all of the "one of these in every box" RFID tags (something to revisit when I'm reimplementing the `/prints` setup UI in #62), but for now I can add something to `/prints` in the same way as we do with the WiFi config tag.

**Comment by george08** [comment]
Sounds good!

(BTW office internet is busted so downloads etc hampered for a bit.)

...
George Oates
Director 
gfns.uk

**Comment by george08** [comment]
This would be helpful in the run-up to Smithsonian config work (prob happening next week).

(Makes me wonder if eventually we'll need a special class of Things/Prints - HQ ones.)

**Comment by amcewen** [comment]
Thinking about this more, it seems (now that a box can have multiple collections) that we should just have a "Museum in a Box" collection that contains the Gillian and then whatever other HQ prints we need.  Maybe one for "check for upgrades" to let us trigger #55?

I did create a new collection for that, and added a Gillian `Thing` but haven't added it to any boxes yet or created any `Print`s for it.

**Comment by george08** [comment]
Good. Wifi too?

...
George Oates
Director 
gfns.uk

**Comment by amcewen** [comment]
Yes and no :-)  The WiFi object is nominally part of this collection, but actually both that and the "check for upgrades" one I mentioned are implemented slightly differently (they don't have any audio data on them) so are included in the `brain` side of things rather than the `heart` Collection side.

**Comment by george08** [comment]
Should we/could we just implement Gill, Wifi, Upgrade to Brain level then? (And not treat them like a Collection on /heart?)

**Comment by amcewen** [comment]
Yes.  Only possible downside to that would be if a Gillian from one box was booped on a different box you wouldn't know that it wasn't that box's own Gillian (you'd get a "Gillian was booped on box X" boop, rather than a "Gillian from box Y was booped on box X" boop), but that doesn't seem especially important to track

**Comment by amcewen** [comment]
They'll all show up as print 650, which is the Gillian welcome object from the [Museum in a Box collection](https://heart.museuminabox.org/heart/collections/104/)

**Comment by amcewen** [comment]
Sadly 650 is the *Thing* ID, not the *Print* ID.  We should use the  *Print* ID of 1839 for the Gillian prints, as that will correctly map to the Gillian *Thing*

See https://github.com/museuminabox/museuminabox-v2/issues/139 for the initial bug report.
