### ISSUE TITLE
Load existing prints on to upgraded Jewish Box

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#69]
Here's the new box:
https://heart.museuminabox.org/heart/boxes/68/

And we need our _existing_ set of prints to play on it:
https://heart.museuminabox.org/backstage/boxes/imprint/243/change/
https://heart.museuminabox.org/backstage/boxes/imprint/231/change/
https://heart.museuminabox.org/backstage/boxes/imprint/229/change/
https://heart.museuminabox.org/backstage/boxes/imprint/227/change/
https://heart.museuminabox.org/backstage/boxes/imprint/225/change/
https://heart.museuminabox.org/backstage/boxes/imprint/223/change/
https://heart.museuminabox.org/backstage/boxes/imprint/221/change/
https://heart.museuminabox.org/backstage/boxes/imprint/220/change/
https://heart.museuminabox.org/backstage/boxes/imprint/226/change/
https://heart.museuminabox.org/backstage/boxes/imprint/230/change/
https://heart.museuminabox.org/backstage/boxes/imprint/228/change/
https://heart.museuminabox.org/backstage/boxes/imprint/222/change/
https://heart.museuminabox.org/backstage/boxes/imprint/224/change/
https://heart.museuminabox.org/backstage/boxes/imprint/232/change/

**Comment by amcewen** [comment]
I've given the original box a UUID which means we can (assuming the stuff I've built works, which it seems to) upgrade it rather than replace the box details (also means new boops will be associated with the same box as the old ones).

Needs testing, with the `img` file I shared in Slack.  @CharlieMiab, if you can burn that image to a spare older 8GB SD card (the latest ones are too small :-() and let me know how you get on, that'd be good.

**Comment by george08** [comment]
Ok, cool. 

Can you please note down the procedure we have to follow in this case?

...
George Oates
Director 
gfns.uk

**Comment by CharlieMiab** [comment]
The prints are now on the upgraded box and the audio has been updated on-site via the Jewish Museum's WiFi. The JM box now has the same script as the Smithsonian boxes and not the custom JM img that Adrian initially custom wrote for it.
