### ISSUE TITLE
Figure out how to get the Box image on more SD cards

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#70]
Should we post, or should you put online somewhere?

Or, you mentioned downloading it from one of the SD cards we have. Is that better? (We weren't sure if we could just copy and paste like that... Charlie's had to use an app to do an install.)

**Comment by amcewen** [comment]
Generally I should put it online, as we've done in the past.  However, I need to get hold of one of the smaller 8GB SD cards that you've got for the latest tranche of boxes, as all of mine are a few bytes too big :-(

If we're expecting the amps order to turn up soon then maybe post one up with them, or otherwise maybe post me one on its own?  That'll let me create the correct size `img` file for you to burn down there.

**Comment by amcewen** [comment]
I've got one of the smallest 8GB cards now, so we can close this.
