### ISSUE TITLE
Sync offline boops with heart when we're next online

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#80]
As we figure out how to get boxes on more wifi, and also figure out how to incorporate boops.csv into central boop log (unless i'm missing that this already happens), it would be nice to show a link to view boops.csv on a Box.

**Comment by amcewen** [comment]
Would it be better to be working towards having the boxes sync their boop log once they're online?  Or is this an interim measure in lieu of that sort of syncing?

One problem, though, of syncing the boop log is that the boxes don't know what time/day it is when they're offline, although what was booped and the duration (once calculated, as we log "started at time X" and "ended at time Y") should be valid

**Comment by george08** [comment]
Yes, it would be better to work on getting boops CSV to sync, and yes, this is an interim measure (because we're not getting an accurate picture of activity until we know we are receiving either live Boop Log data or a full boop CSV from every box).

I really hope we don't have to install a clock in a box! ;)

**Comment by george08** [comment]
I guess we're stuck on getting any kind of sync without an internet connection anyway... _unless_ we can send hardy school folks to box.local to download a CSV to send to us.

**Comment by george08** [comment]
Not sure what to do with this one - if we require a clock, that's one new issue. The requirement I'm wanting is that all boop logs get to sent to the DB as much as possible. (While acknowledging that's not possible if the box never goes online.)

**Comment by amcewen** [comment]
We could make the CSV easier to get to as a backup for getting *some* stats out, because at present you'd need to `ssh` into the box and that isn't very friendly.

As you say, we'd need to add a clock for proper stats.  Maybe keep this issue to just make it easier for people to get the CSV at a later date - so that'd let us/them find out find out which objects are most popular, and how long they're booped for, which is useful even if you don't know exactly when all the boops happened.  And then spin out the "add clock module" for a future version.

We could add an option in `heart` to let someone upload a CSV and build a `datasette` instance to poke around with the data, or something similar?  As a halfway house to proper boop log sync/integration...

**Comment by george08** [comment]
(I've been idly wondering whether we could use Slack for "messaging" the boop log... This is probably madness.)

**Comment by amcewen** [comment]
That *definitely* won't work if the box isn't online, the "New Issue" button is up there :point_up: ;-)

Feels like that would just require more code to then parse and pull it down.  Plus, it'll soon be overwhelmed with too many boops, right? :-D

**Comment by george08** [comment]
We're going to need this feature for an upcoming grant (if we're successful). We should know if we're successful by end of March... so, may be worth making its own (smaller) release.

Are you OK with that @amcewen ?

**Comment by amcewen** [comment]
Have [migrated this to the new repo](https://github.com/museuminabox/brain-dei-mille/issues/45)
