### ISSUE TITLE
Make progress LEDs twinkle if there's an update happening

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#89]
I'm working on the Swedish National Heritage Board's box for delivery. The collection they made had five things in it, and then they added another four. I've added the four new things using the admin UI, and checked it on Heart, and all seems well.

https://heart.museuminabox.org/heart/collections/105/

But, when I go to configure the stickers on the box a) I can't see the new things in the list on /prints, and b) I don't know if the box is trying to update itself. (I've restarted the box three times now, and the new things aren't showing up on /prints, still.)

**Comment by george08** [comment]
Maybe we could even have the box speak, and say "Checking for updates. One moment, please."

**Comment by amcewen** [comment]
The things-not-showing-up-in-`/prints` is covered in #90.

By "update", I'm assuming you mean downloading-new-audio-files (as that's all that updating the set of prints means to the `brain`), rather than putting-new-software-onto-the-`brain`.

I'm going to make #49 a bit more general, and we can group together all of the "LEDs to indicate things happening" discussion there.
