### ISSUE TITLE
If you put an object back on the Box within (2 seconds?), keep playing the track where it left off

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#94]
This is a nice to have - was a suggestion that came up testing with someone for the first time... It doesn't take too long to learn that the track starts from the beginning, but perhaps, if you put the object back on quickly, maybe it could keep playing.

**Comment by amcewen** [comment]
That'll be hard to do unless we waited for two seconds from someone removing the object (because the software doesn't know where it is in the audio playback in order to jump to the right place to start again).  It might (wouldn't be a trivial amount of work, because currently it doesn't care about talking to the playback process) be possible to have it pause the playback, and then stop if fully it if the object hasn't been replaced in a few seconds.  Would need to see how tricky it is to do the pause/resume.

**Comment by george08** [comment]
I don't think we need this. If it comes up again, we can reassess.
